---
  - hosts: 172.31.23.147
    become: yes
    tasks:
    - name: I want to excute my linux command
      command: hostname -f
      register: myfirsttaskresult

    - name: I want to display the myfirsttaskresult
      debug: 
        msg: "{{myfirsttaskresult}}"